apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo
  namespace: fika

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: fika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
      version: v1
  template:
    metadata:
      labels:
        app: foo
        version: v1
    spec:
      serviceAccountName: foo
      containers:
      - image: docker.io/asayahtest/foo
        imagePullPolicy: IfNotPresent
        name: foo
        ports:
        - containerPort: 8080