---
apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: fika
  labels:
    app: foo
    service: foo
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: foo